# NOTE: this release is compatible with Kubernetes versions v1.9 - v1.12

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: yandex-cloud-controller-manager
  name: yandex-cloud
  namespace: kube-system
stringData:
  access-token: "REPLACE WITH YANDEX.CLOUD ACCESS TOKEN"
  folder-id: "REPLACE WITH YANDEX.CLOUD FOLDER ID"
